name: Download and Push File

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at UTC midnight

jobs:
  download_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout city-of-toronto-short-term-rentals-registration 
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_CITYOFTORONTOSHORTTERMRENTALSREGISTR }}
          repository: 'RamVasuthevan/city-of-toronto-short-term-rentals-registration '
          path: city-of-toronto-short-term-rentals-registration 
          ref: 'main'

      - name: Download File
        run: |
              curl -o city-of-toronto-short-term-rentals-registration/short-term-rental-registrations-data.csv https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/2ab20f80-3599-486a-8f8a-9cb59117977c/resource/9c235257-b09f-441e-bcad-1495607f9a82/download/short-term-rental-registrations-data.csv      
      
      - name: Commit and Push if Files Changed
        run: |
          cd city-of-toronto-short-term-rentals-registration
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add short-term-rental-registrations-data.csv
          timestamp=$(date -u)
          git commit -m "Downloaded: ${timestamp}: commit: ${{github.sha}}" || exit 0
          # Use force push to push changes
          git push --force